package com.trang.QuanLyNhanVien.mapper;

import com.trang.QuanLyNhanVien.model.Employees;
import com.trang.QuanLyNhanVien.model.EmployeesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface EmployeesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Tue Feb 08 11:52:47 ICT 2022
	 */
	long countByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Tue Feb 08 11:52:47 ICT 2022
	 */
	int deleteByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Tue Feb 08 11:52:47 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Tue Feb 08 11:52:47 ICT 2022
	 */
	int insert(Employees record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Tue Feb 08 11:52:47 ICT 2022
	 */
	int insertSelective(Employees record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Tue Feb 08 11:52:47 ICT 2022
	 */
	List<Employees> selectByExample(EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Tue Feb 08 11:52:47 ICT 2022
	 */
	Employees selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Tue Feb 08 11:52:47 ICT 2022
	 */
	int updateByExampleSelective(@Param("record") Employees record, @Param("example") EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Tue Feb 08 11:52:47 ICT 2022
	 */
	int updateByExample(@Param("record") Employees record, @Param("example") EmployeesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Tue Feb 08 11:52:47 ICT 2022
	 */
	int updateByPrimaryKeySelective(Employees record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employees
	 * @mbg.generated  Tue Feb 08 11:52:47 ICT 2022
	 */
	int updateByPrimaryKey(Employees record);

	List<Employees> selectEmployees();
}