package com.trang.QuanLyNhanVien.mapper;

import com.trang.QuanLyNhanVien.model.Role;
import com.trang.QuanLyNhanVien.model.RoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface RoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	long countByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	int deleteByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	int insertSelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	List<Role> selectByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);
	Role SelectById(int id);
}