package com.trang.QuanLyNhanVien.model;

public class Employees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.id
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.name
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.phone
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.address
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.age
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.id
     *
     * @return the value of employees.id
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.id
     *
     * @param id the value for employees.id
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.name
     *
     * @return the value of employees.name
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.name
     *
     * @param name the value for employees.name
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.phone
     *
     * @return the value of employees.phone
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.phone
     *
     * @param phone the value for employees.phone
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.address
     *
     * @return the value of employees.address
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.address
     *
     * @param address the value for employees.address
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.age
     *
     * @return the value of employees.age
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.age
     *
     * @param age the value for employees.age
     *
     * @mbg.generated Fri Jan 21 15:03:38 ICT 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}