package com.trang.QuanLyNhanVien.model;

public class Employees {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.id
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.name
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.phone
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.address
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.age
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.img
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.password
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.username
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employees.roleid
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	private Integer roleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.id
	 * @return  the value of employees.id
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.id
	 * @param id  the value for employees.id
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.name
	 * @return  the value of employees.name
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.name
	 * @param name  the value for employees.name
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.phone
	 * @return  the value of employees.phone
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.phone
	 * @param phone  the value for employees.phone
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.address
	 * @return  the value of employees.address
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.address
	 * @param address  the value for employees.address
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.age
	 * @return  the value of employees.age
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.age
	 * @param age  the value for employees.age
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.img
	 * @return  the value of employees.img
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.img
	 * @param img  the value for employees.img
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.password
	 * @return  the value of employees.password
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.password
	 * @param password  the value for employees.password
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.username
	 * @return  the value of employees.username
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.username
	 * @param username  the value for employees.username
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employees.roleid
	 * @return  the value of employees.roleid
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employees.roleid
	 * @param roleid  the value for employees.roleid
	 * @mbg.generated  Fri Feb 11 10:01:11 ICT 2022
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}
}